application: votay
version: 1
runtime: python
api_version: 1

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /admin.*
  script: admin/admin.py

- url: /.*
  script: home/home.py
  
- url: .*
  script: main.py
