application: fictionhelp
version: 1
runtime: python
api_version: 1

default_expiration: "1d 1h"

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /javascript
  static_dir: static/javascript

- url: /admin.*
  script: admin/admin.py
  login: admin

- url: /robots.txt
  script: main.py

- url: /set-name.*
  script: home/set_name.py
  login: required

- url: /.*
  script: home/home.py
  
- url: .*
  script: main.py
